create make target for building release bundle

diff --git a/admin/smv-release b/admin/smv-release
--- a/admin/smv-release
+++ b/admin/smv-release
@@ -109,13 +109,15 @@ function validate_version()
   fi
 }
 
-function build_local_docker_image()
+function create_base_docker_image()
 {
   info "building local docker image"
 
+  BASE_DOCKER_IMAGE=smv-base-${SMV_VERSION}
+
   cd "${SMV_DIR}/docker/smv"
   # build local docker image tag as `local_docker_build`
-  docker build -t local_docker_build . >> ${LOGFILE} 2>&1 || error "local docker build failed"
+  docker build -t ${BASE_DOCKER_IMAGE} . >> ${LOGFILE} 2>&1 || error "local docker build failed"
 }
 
 function run_make_in_docker()
@@ -128,7 +130,7 @@ function run_make_in_docker()
 
   # explicitly add -ivy flag as SMV docker image is not picking up sbtopts file. (SMV issue #556)
   docker run --rm -it -v ${PROJ_DIR}:/projects local_docker_build \
-    sh -c "${docker_cmd}" >> ${LOGFILE} 2>&1 || error "SMV sbt $target failed"
+    sh -c "${docker_cmd}" >> ${LOGFILE} 2>&1 || error "SMV make $target failed"
 }
 
 function build_smv()
@@ -219,18 +221,7 @@ function create_tar()
 {
   info "create tar image"
 
-  # cleanup some unneeded binary files.
-  rm -rf "${SMV_DIR}/project/target" "${SMV_DIR}/project/project"
-  rm -rf "${SMV_DIR}/target/resolution-cache" "${SMV_DIR}/target/streams"
-  # use the `find ... -exec` variant instead of xargs
-  # because we don't want `rm` to execute if `find` returns nothing
-  find "${SMV_DIR}/target" -name '*with-dependencies.jar' -prune -o -type f -exec rm -f \{\} +
-  find "${SMV_DIR}/src" -name '*.pyc' -exec rm -f \{\} +
-  find "${SMV_DIR}/src" -name '__pycache__' -exec rm -rf \{\} +
-
-  # create the tar image
-  ${TAR} zcvf "${TGZ_IMAGE}" -C "${PROJ_DIR}" --exclude=.git --exclude="admin" \
-    ${SMV_DIR_BASE} >> ${LOGFILE} 2>&1 || error "tar creation failed"
+  run_make_in_docker bundle
 }
 
 # This only creates the release and does NOT attach the zip asset to it.
@@ -280,7 +271,7 @@ function attach_tar_to_github_release()
 
 }
 
-function create_docker_image()
+function create_smv_docker_image()
 {
   local tag=v"$SMV_VERSION"
 
@@ -290,7 +281,8 @@ function create_docker_image()
   docker login -u ${DOCKERHUB_USER_NAME} -p ${DOCKERHUB_USER_PASSWORD}
 
   info "building docker image"
-  docker build -t docker_build . >> ${LOGFILE} 2>&1 || error "docker build failed"
+  docker build --build-arg SMV_BASE_IMAGE=${BASE_DOCKER_IMAGE} --build-arg SMV_BUNDLE=${TGZ_IMAGE} \
+    -t docker_build . >> ${LOGFILE} 2>&1 || error "docker build failed"
 
   info "pushing new tagged docker image (${tag})"
   docker tag docker_build tresamigos/smv:${tag} >> ${LOGFILE} 2>&1 || error "docker tag failed"
@@ -410,7 +402,7 @@ check_for_existing_tag
 get_prev_smv_version
 find_gnu_tar
 find_release_msg_file
-build_local_docker_image
+create_base_docker_image
 build_smv
 test_smv
 gen_pydocs
@@ -418,10 +410,10 @@ gen_scaladocs
 update_version
 tag_release
 create_tar
+create_smv_docker_image
 create_github_release
 attach_tar_to_github_release
 get_latest_ghpages
 update_ghpages_docs
 push_ghpages_docs
-create_docker_image
 info "Finish Release on: $(date)"
